#include "ParameterNames.h"

// Slices
const std::string ParameterNames::sliceProbability[128] = {
    "SliceProbability0",
    "SliceProbability1",
    "SliceProbability2",
    "SliceProbability3",
    "SliceProbability4",
    "SliceProbability5",
    "SliceProbability6",
    "SliceProbability7",
    "SliceProbability8",
    "SliceProbability9",
    "SliceProbability10",
    "SliceProbability11",
    "SliceProbability12",
    "SliceProbability13",
    "SliceProbability14",
    "SliceProbability15",
    "SliceProbability16",
    "SliceProbability17",
    "SliceProbability18",
    "SliceProbability19",
    "SliceProbability20",
    "SliceProbability21",
    "SliceProbability22",
    "SliceProbability23",
    "SliceProbability24",
    "SliceProbability25",
    "SliceProbability26",
    "SliceProbability27",
    "SliceProbability28",
    "SliceProbability29",
    "SliceProbability30",
    "SliceProbability31",
    "SliceProbability32",
    "SliceProbability33",
    "SliceProbability34",
    "SliceProbability35",
    "SliceProbability36",
    "SliceProbability37",
    "SliceProbability38",
    "SliceProbability39",
    "SliceProbability40",
    "SliceProbability41",
    "SliceProbability42",
    "SliceProbability43",
    "SliceProbability44",
    "SliceProbability45",
    "SliceProbability46",
    "SliceProbability47",
    "SliceProbability48",
    "SliceProbability49",
    "SliceProbability50",
    "SliceProbability51",
    "SliceProbability52",
    "SliceProbability53",
    "SliceProbability54",
    "SliceProbability55",
    "SliceProbability56",
    "SliceProbability57",
    "SliceProbability58",
    "SliceProbability59",
    "SliceProbability60",
    "SliceProbability61",
    "SliceProbability62",
    "SliceProbability63",
    "SliceProbability64",
    "SliceProbability65",
    "SliceProbability66",
    "SliceProbability67",
    "SliceProbability68",
    "SliceProbability69",
    "SliceProbability70",
    "SliceProbability71",
    "SliceProbability72",
    "SliceProbability73",
    "SliceProbability74",
    "SliceProbability75",
    "SliceProbability76",
    "SliceProbability77",
    "SliceProbability78",
    "SliceProbability79",
    "SliceProbability80",
    "SliceProbability81",
    "SliceProbability82",
    "SliceProbability83",
    "SliceProbability84",
    "SliceProbability85",
    "SliceProbability86",
    "SliceProbability87",
    "SliceProbability88",
    "SliceProbability89",
    "SliceProbability90",
    "SliceProbability91",
    "SliceProbability92",
    "SliceProbability93",
    "SliceProbability94",
    "SliceProbability95",
    "SliceProbability96",
    "SliceProbability97",
    "SliceProbability98",
    "SliceProbability99",
    "SliceProbability100",
    "SliceProbability101",
    "SliceProbability102",
    "SliceProbability103",
    "SliceProbability104",
    "SliceProbability105",
    "SliceProbability106",
    "SliceProbability107",
    "SliceProbability108",
    "SliceProbability109",
    "SliceProbability110",
    "SliceProbability111",
    "SliceProbability112",
    "SliceProbability113",
    "SliceProbability114",
    "SliceProbability115",
    "SliceProbability116",
    "SliceProbability117",
    "SliceProbability118",
    "SliceProbability119",
    "SliceProbability120",
    "SliceProbability121",
    "SliceProbability122",
    "SliceProbability123",
    "SliceProbability124",
    "SliceProbability125",
    "SliceProbability126",
    "SliceProbability127"
};

const std::string ParameterNames::sliceLength[128] = {
    "SliceLength0",
    "SliceLength1",
    "SliceLength2",
    "SliceLength3",
    "SliceLength4",
    "SliceLength5",
    "SliceLength6",
    "SliceLength7",
    "SliceLength8",
    "SliceLength9",
    "SliceLength10",
    "SliceLength11",
    "SliceLength12",
    "SliceLength13",
    "SliceLength14",
    "SliceLength15",
    "SliceLength16",
    "SliceLength17",
    "SliceLength18",
    "SliceLength19",
    "SliceLength20",
    "SliceLength21",
    "SliceLength22",
    "SliceLength23",
    "SliceLength24",
    "SliceLength25",
    "SliceLength26",
    "SliceLength27",
    "SliceLength28",
    "SliceLength29",
    "SliceLength30",
    "SliceLength31",
    "SliceLength32",
    "SliceLength33",
    "SliceLength34",
    "SliceLength35",
    "SliceLength36",
    "SliceLength37",
    "SliceLength38",
    "SliceLength39",
    "SliceLength40",
    "SliceLength41",
    "SliceLength42",
    "SliceLength43",
    "SliceLength44",
    "SliceLength45",
    "SliceLength46",
    "SliceLength47",
    "SliceLength48",
    "SliceLength49",
    "SliceLength50",
    "SliceLength51",
    "SliceLength52",
    "SliceLength53",
    "SliceLength54",
    "SliceLength55",
    "SliceLength56",
    "SliceLength57",
    "SliceLength58",
    "SliceLength59",
    "SliceLength60",
    "SliceLength61",
    "SliceLength62",
    "SliceLength63",
    "SliceLength64",
    "SliceLength65",
    "SliceLength66",
    "SliceLength67",
    "SliceLength68",
    "SliceLength69",
    "SliceLength70",
    "SliceLength71",
    "SliceLength72",
    "SliceLength73",
    "SliceLength74",
    "SliceLength75",
    "SliceLength76",
    "SliceLength77",
    "SliceLength78",
    "SliceLength79",
    "SliceLength80",
    "SliceLength81",
    "SliceLength82",
    "SliceLength83",
    "SliceLength84",
    "SliceLength85",
    "SliceLength86",
    "SliceLength87",
    "SliceLength88",
    "SliceLength89",
    "SliceLength90",
    "SliceLength91",
    "SliceLength92",
    "SliceLength93",
    "SliceLength94",
    "SliceLength95",
    "SliceLength96",
    "SliceLength97",
    "SliceLength98",
    "SliceLength99",
    "SliceLength100",
    "SliceLength101",
    "SliceLength102",
    "SliceLength103",
    "SliceLength104",
    "SliceLength105",
    "SliceLength106",
    "SliceLength107",
    "SliceLength108",
    "SliceLength109",
    "SliceLength110",
    "SliceLength111",
    "SliceLength112",
    "SliceLength113",
    "SliceLength114",
    "SliceLength115",
    "SliceLength116",
    "SliceLength117",
    "SliceLength118",
    "SliceLength119",
    "SliceLength120",
    "SliceLength121",
    "SliceLength122",
    "SliceLength123",
    "SliceLength124",
    "SliceLength125",
    "SliceLength126",
    "SliceLength127"
};

const std::string ParameterNames::sliceEnabled[128] = {
    "SliceEnabled0",
    "SliceEnabled1",
    "SliceEnabled2",
    "SliceEnabled3",
    "SliceEnabled4",
    "SliceEnabled5",
    "SliceEnabled6",
    "SliceEnabled7",
    "SliceEnabled8",
    "SliceEnabled9",
    "SliceEnabled10",
    "SliceEnabled11",
    "SliceEnabled12",
    "SliceEnabled13",
    "SliceEnabled14",
    "SliceEnabled15",
    "SliceEnabled16",
    "SliceEnabled17",
    "SliceEnabled18",
    "SliceEnabled19",
    "SliceEnabled20",
    "SliceEnabled21",
    "SliceEnabled22",
    "SliceEnabled23",
    "SliceEnabled24",
    "SliceEnabled25",
    "SliceEnabled26",
    "SliceEnabled27",
    "SliceEnabled28",
    "SliceEnabled29",
    "SliceEnabled30",
    "SliceEnabled31",
    "SliceEnabled32",
    "SliceEnabled33",
    "SliceEnabled34",
    "SliceEnabled35",
    "SliceEnabled36",
    "SliceEnabled37",
    "SliceEnabled38",
    "SliceEnabled39",
    "SliceEnabled40",
    "SliceEnabled41",
    "SliceEnabled42",
    "SliceEnabled43",
    "SliceEnabled44",
    "SliceEnabled45",
    "SliceEnabled46",
    "SliceEnabled47",
    "SliceEnabled48",
    "SliceEnabled49",
    "SliceEnabled50",
    "SliceEnabled51",
    "SliceEnabled52",
    "SliceEnabled53",
    "SliceEnabled54",
    "SliceEnabled55",
    "SliceEnabled56",
    "SliceEnabled57",
    "SliceEnabled58",
    "SliceEnabled59",
    "SliceEnabled60",
    "SliceEnabled61",
    "SliceEnabled62",
    "SliceEnabled63",
    "SliceEnabled64",
    "SliceEnabled65",
    "SliceEnabled66",
    "SliceEnabled67",
    "SliceEnabled68",
    "SliceEnabled69",
    "SliceEnabled70",
    "SliceEnabled71",
    "SliceEnabled72",
    "SliceEnabled73",
    "SliceEnabled74",
    "SliceEnabled75",
    "SliceEnabled76",
    "SliceEnabled77",
    "SliceEnabled78",
    "SliceEnabled79",
    "SliceEnabled80",
    "SliceEnabled81",
    "SliceEnabled82",
    "SliceEnabled83",
    "SliceEnabled84",
    "SliceEnabled85",
    "SliceEnabled86",
    "SliceEnabled87",
    "SliceEnabled88",
    "SliceEnabled89",
    "SliceEnabled90",
    "SliceEnabled91",
    "SliceEnabled92",
    "SliceEnabled93",
    "SliceEnabled94",
    "SliceEnabled95",
    "SliceEnabled96",
    "SliceEnabled97",
    "SliceEnabled98",
    "SliceEnabled99",
    "SliceEnabled100",
    "SliceEnabled101",
    "SliceEnabled102",
    "SliceEnabled103",
    "SliceEnabled104",
    "SliceEnabled105",
    "SliceEnabled106",
    "SliceEnabled107",
    "SliceEnabled108",
    "SliceEnabled109",
    "SliceEnabled110",
    "SliceEnabled111",
    "SliceEnabled112",
    "SliceEnabled113",
    "SliceEnabled114",
    "SliceEnabled115",
    "SliceEnabled116",
    "SliceEnabled117",
    "SliceEnabled118",
    "SliceEnabled119",
    "SliceEnabled120",
    "SliceEnabled121",
    "SliceEnabled122",
    "SliceEnabled123",
    "SliceEnabled124",
    "SliceEnabled125",
    "SliceEnabled126",
    "SliceEnabled127"
};

const std::string ParameterNames::slicePlusSixteen[128] = {
    "slicePlusSixteen0",
    "slicePlusSixteen1",
    "slicePlusSixteen2",
    "slicePlusSixteen3",
    "slicePlusSixteen4",
    "slicePlusSixteen5",
    "slicePlusSixteen6",
    "slicePlusSixteen7",
    "slicePlusSixteen8",
    "slicePlusSixteen9",
    "slicePlusSixteen10",
    "slicePlusSixteen11",
    "slicePlusSixteen12",
    "slicePlusSixteen13",
    "slicePlusSixteen14",
    "slicePlusSixteen15",
    "slicePlusSixteen16",
    "slicePlusSixteen17",
    "slicePlusSixteen18",
    "slicePlusSixteen19",
    "slicePlusSixteen20",
    "slicePlusSixteen21",
    "slicePlusSixteen22",
    "slicePlusSixteen23",
    "slicePlusSixteen24",
    "slicePlusSixteen25",
    "slicePlusSixteen26",
    "slicePlusSixteen27",
    "slicePlusSixteen28",
    "slicePlusSixteen29",
    "slicePlusSixteen30",
    "slicePlusSixteen31",
    "slicePlusSixteen32",
    "slicePlusSixteen33",
    "slicePlusSixteen34",
    "slicePlusSixteen35",
    "slicePlusSixteen36",
    "slicePlusSixteen37",
    "slicePlusSixteen38",
    "slicePlusSixteen39",
    "slicePlusSixteen40",
    "slicePlusSixteen41",
    "slicePlusSixteen42",
    "slicePlusSixteen43",
    "slicePlusSixteen44",
    "slicePlusSixteen45",
    "slicePlusSixteen46",
    "slicePlusSixteen47",
    "slicePlusSixteen48",
    "slicePlusSixteen49",
    "slicePlusSixteen50",
    "slicePlusSixteen51",
    "slicePlusSixteen52",
    "slicePlusSixteen53",
    "slicePlusSixteen54",
    "slicePlusSixteen55",
    "slicePlusSixteen56",
    "slicePlusSixteen57",
    "slicePlusSixteen58",
    "slicePlusSixteen59",
    "slicePlusSixteen60",
    "slicePlusSixteen61",
    "slicePlusSixteen62",
    "slicePlusSixteen63",
    "slicePlusSixteen64",
    "slicePlusSixteen65",
    "slicePlusSixteen66",
    "slicePlusSixteen67",
    "slicePlusSixteen68",
    "slicePlusSixteen69",
    "slicePlusSixteen70",
    "slicePlusSixteen71",
    "slicePlusSixteen72",
    "slicePlusSixteen73",
    "slicePlusSixteen74",
    "slicePlusSixteen75",
    "slicePlusSixteen76",
    "slicePlusSixteen77",
    "slicePlusSixteen78",
    "slicePlusSixteen79",
    "slicePlusSixteen80",
    "slicePlusSixteen81",
    "slicePlusSixteen82",
    "slicePlusSixteen83",
    "slicePlusSixteen84",
    "slicePlusSixteen85",
    "slicePlusSixteen86",
    "slicePlusSixteen87",
    "slicePlusSixteen88",
    "slicePlusSixteen89",
    "slicePlusSixteen90",
    "slicePlusSixteen91",
    "slicePlusSixteen92",
    "slicePlusSixteen93",
    "slicePlusSixteen94",
    "slicePlusSixteen95",
    "slicePlusSixteen96",
    "slicePlusSixteen97",
    "slicePlusSixteen98",
    "slicePlusSixteen99",
    "slicePlusSixteen100",
    "slicePlusSixteen101",
    "slicePlusSixteen102",
    "slicePlusSixteen103",
    "slicePlusSixteen104",
    "slicePlusSixteen105",
    "slicePlusSixteen106",
    "slicePlusSixteen107",
    "slicePlusSixteen108",
    "slicePlusSixteen109",
    "slicePlusSixteen110",
    "slicePlusSixteen111",
    "slicePlusSixteen112",
    "slicePlusSixteen113",
    "slicePlusSixteen114",
    "slicePlusSixteen115",
    "slicePlusSixteen116",
    "slicePlusSixteen117",
    "slicePlusSixteen118",
    "slicePlusSixteen119",
    "slicePlusSixteen120",
    "slicePlusSixteen121",
    "slicePlusSixteen122",
    "slicePlusSixteen123",
    "slicePlusSixteen124",
    "slicePlusSixteen125",
    "slicePlusSixteen126",
    "slicePlusSixteen127"
};

// Strips
const std::string ParameterNames::stripProbability[32] = {
    "StripProbability0",
    "StripProbability1",
    "StripProbability2",
    "StripProbability3",
    "StripProbability4",
    "StripProbability5",
    "StripProbability6",
    "StripProbability7",
    "StripProbability8",
    "StripProbability9",
    "StripProbability10",
    "StripProbability11",
    "StripProbability12",
    "StripProbability13",
    "StripProbability14",
    "StripProbability15",
    "StripProbability16",
    "StripProbability17",
    "StripProbability18",
    "StripProbability19",
    "StripProbability20",
    "StripProbability21",
    "StripProbability22",
    "StripProbability23",
    "StripProbability24",
    "StripProbability25",
    "StripProbability26",
    "StripProbability27",
    "StripProbability28",
    "StripProbability29",
    "StripProbability30",
    "StripProbability31"
};

const std::string ParameterNames::stripGroup[32] = {
    "StripGroup0",
    "StripGroup1",
    "StripGroup2",
    "StripGroup3",
    "StripGroup4",
    "StripGroup5",
    "StripGroup6",
    "StripGroup7",
    "StripGroup8",
    "StripGroup9",
    "StripGroup10",
    "StripGroup11",
    "StripGroup12",
    "StripGroup13",
    "StripGroup14",
    "StripGroup15",
    "StripGroup16",
    "StripGroup17",
    "StripGroup18",
    "StripGroup19",
    "StripGroup20",
    "StripGroup21",
    "StripGroup22",
    "StripGroup23",
    "StripGroup24",
    "StripGroup25",
    "StripGroup26",
    "StripGroup27",
    "StripGroup28",
    "StripGroup29",
    "StripGroup30",
    "StripGroup31"
};

const std::string ParameterNames::stripChoice[32] = {
    "StripChoice0",
    "StripChoice1",
    "StripChoice2",
    "StripChoice3",
    "StripChoice4",
    "StripChoice5",
    "StripChoice6",
    "StripChoice7",
    "StripChoice8",
    "StripChoice9",
    "StripChoice10",
    "StripChoice11",
    "StripChoice12",
    "StripChoice13",
    "StripChoice14",
    "StripChoice15",
    "StripChoice16",
    "StripChoice17",
    "StripChoice18",
    "StripChoice19",
    "StripChoice20",
    "StripChoice21",
    "StripChoice22",
    "StripChoice23",
    "StripChoice24",
    "StripChoice25",
    "StripChoice26",
    "StripChoice27",
    "StripChoice28",
    "StripChoice29",
    "StripChoice30",
    "StripChoice31"
};

const std::string ParameterNames::stripNote[32] = {
    "StripNote0",
    "StripNote1",
    "StripNote2",
    "StripNote3",
    "StripNote4",
    "StripNote5",
    "StripNote6",
    "StripNote7",
    "StripNote8",
    "StripNote9",
    "StripNote10",
    "StripNote11",
    "StripNote12",
    "StripNote13",
    "StripNote14",
    "StripNote15",
    "StripNote16",
    "StripNote17",
    "StripNote18",
    "StripNote19",
    "StripNote20",
    "StripNote21",
    "StripNote22",
    "StripNote23",
    "StripNote24",
    "StripNote25",
    "StripNote26",
    "StripNote27",
    "StripNote28",
    "StripNote29",
    "StripNote30",
    "StripNote31"
};

const std::string ParameterNames::stripEnabled[32] = {
    "StripEnabled0",
    "StripEnabled1",
    "StripEnabled2",
    "StripEnabled3",
    "StripEnabled4",
    "StripEnabled5",
    "StripEnabled6",
    "StripEnabled7",
    "StripEnabled8",
    "StripEnabled9",
    "StripEnabled10",
    "StripEnabled11",
    "StripEnabled12",
    "StripEnabled13",
    "StripEnabled14",
    "StripEnabled15",
    "StripEnabled16",
    "StripEnabled17",
    "StripEnabled18",
    "StripEnabled19",
    "StripEnabled20",
    "StripEnabled21",
    "StripEnabled22",
    "StripEnabled23",
    "StripEnabled24",
    "StripEnabled25",
    "StripEnabled26",
    "StripEnabled27",
    "StripEnabled28",
    "StripEnabled29",
    "StripEnabled30",
    "StripEnabled31"
};

const std::string ParameterNames::stripBypassed[32] = {
    "StripBypassed0",
    "StripBypassed1",
    "StripBypassed2",
    "StripBypassed3",
    "StripBypassed4",
    "StripBypassed5",
    "StripBypassed6",
    "StripBypassed7",
    "StripBypassed8",
    "StripBypassed9",
    "StripBypassed10",
    "StripBypassed11",
    "StripBypassed12",
    "StripBypassed13",
    "StripBypassed14",
    "StripBypassed15",
    "StripBypassed16",
    "StripBypassed17",
    "StripBypassed18",
    "StripBypassed19",
    "StripBypassed20",
    "StripBypassed21",
    "StripBypassed22",
    "StripBypassed23",
    "StripBypassed24",
    "StripBypassed25",
    "StripBypassed26",
    "StripBypassed27",
    "StripBypassed28",
    "StripBypassed29",
    "StripBypassed30",
    "StripBypassed31"
};

const std::string ParameterNames::groupLength[NUM_GROUPS] = {
    "groupLength0",
    "groupLength1",
    "groupLength2",
    "groupLength3"
};

const std::string ParameterNames::groupPlusSixteen[NUM_GROUPS] = {
    "groupPlusSixteen0",
    "groupPlusSixteen1",
    "groupPlusSixteen2",
    "groupPlusSixteen3"
};

const std::string ParameterNames::groupEnabled[NUM_GROUPS] = {
    "groupEnabled0",
    "groupEnabled1",
    "groupEnabled2",
    "groupEnabled3"
};

// Parameter Options
const juce::StringArray ParameterOptions::toggleButtonOptions = {
    "On",
    "Off"
};

const juce::StringArray ParameterOptions::groupOptions = {
    "1", "2", "3", "4"
};

const juce::StringArray ParameterOptions::choiceOptions = {
    "1", "2", "3", "4", "5", "6", "7", "8"
};

const juce::StringArray ParameterOptions::lengthOptions = {
    "1", "2", "3", "4", "5", "6", "7", "8", 
    "9", "10", "11", "12", "13", "14", "15", "16"
};

const juce::StringArray ParameterOptions::plusSixteenOptions = {
    "+0", "+16", "+32", "+48", "+64", "+80", "+96", "+112", "+128"
};

// Colours
//==============================================================================
// (49D49D);
const juce::Colour Colours::aquamarine =        
    juce::Colour(73, 212, 157);

// (BFD7B5);
const juce::Colour Colours::teaGreen =          
    juce::Colour(191, 215, 181); 

// (E7EFC5);
const juce::Colour Colours::springBud =         
    juce::Colour(231, 239, 197); 

// (F2DDA4);
const juce::Colour Colours::champagne =         
    juce::Colour(242, 221, 164); 

// (A29F15);
const juce::Colour Colours::citron =            
    juce::Colour(162, 159, 21); 

// (E26D5C);
const juce::Colour Colours::terraCotta =        
    juce::Colour(226, 109, 92); 

// (0x0d1016);
const juce::Colour Colours::background1 =       
    juce::Colour(13, 16, 22); 

// (0x00010a);
const juce::Colour Colours::background2 =       
    juce::Colour(0, 1, 10); 

// (0xdaade0);
const juce::Colour Colours::lilac =             
    juce::Colour(218, 173, 224); 

// (0xee68af);
const juce::Colour Colours::pink =              
    juce::Colour(238, 104, 175); 

// (0xf5bb6c);
const juce::Colour Colours::orange2 =           
    juce::Colour(245, 187, 108); 

// (0xfdc68a);
const juce::Colour Colours::orange1 =           
    juce::Colour(253, 198, 138); 

// (0xf7cb8b);
const juce::Colour Colours::orange3 =           
    juce::Colour(247, 203, 139);  

// (0x292d36);
const juce::Colour Colours::grid1 =             
    juce::Colour::fromRGBA(41, 45, 54, 50); 

// (0x3d424d);
const juce::Colour Colours::grid2 =             
    juce::Colour::fromRGBA(61, 66, 77, 50); 

// (0xb3b1ad);
const juce::Colour Colours::grid3 =             
    juce::Colour(179, 177, 173);

// (0xee68af);
const juce::Colour Colours::transparentPink =
juce::Colour::fromRGBA(238, 104, 175, 100);

// (0xdaade0);
const juce::Colour Colours::transparentLilac =
juce::Colour::fromRGBA(218, 173, 224, 100);

// (A29F15);
const juce::Colour Colours::transparentCitron =
juce::Colour::fromRGBA(162, 159, 21, 100);

// (0x00010a);
const juce::Colour Colours::transparentBackground2 = 
    juce::Colour::fromRGBA(0, 1, 10, 80); 

// (0xf7cb8b);
const juce::Colour Colours::transparentOrange3 = 
    juce::Colour::fromRGBA(247, 203, 139, 60); 

// (0xf7cb8b);
const juce::Colour Colours::transparentOrange4 =
juce::Colour::fromRGBA(247, 203, 139, 20);

// (0xfdc68a);
const juce::Colour Colours::transparentOrange1 =
    juce::Colour::fromRGBA(253, 198, 138, 60);